//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogAnalyzer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LogAnalyzer.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Analyzer.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average load time.
        /// </summary>
        public static string AverageLoadTimeLists {
            get {
                return ResourceManager.GetString("AverageLoadTimeLists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operations by document types.
        /// </summary>
        public static string ByDocumentTypesHeader {
            get {
                return ResourceManager.GetString("ByDocumentTypesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client operations that grouped by document types and kinds..
        /// </summary>
        public static string ByDocumentTypesTooltip {
            get {
                return ResourceManager.GetString("ByDocumentTypesTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operations by users.
        /// </summary>
        public static string ByUsersHeader {
            get {
                return ResourceManager.GetString("ByUsersHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client operations that grouped by users. Here you&apos;ll be able to find the most active users..
        /// </summary>
        public static string ByUsersTooltip {
            get {
                return ResourceManager.GetString("ByUsersTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created amount.
        /// </summary>
        public static string CreatedDocuments {
            get {
                return ResourceManager.GetString("CreatedDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create operations amount.
        /// </summary>
        public static string CreatedEntities {
            get {
                return ResourceManager.GetString("CreatedEntities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details ».
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edited amount.
        /// </summary>
        public static string EditedDocuments {
            get {
                return ResourceManager.GetString("EditedDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit operations amount.
        /// </summary>
        public static string EditedEntities {
            get {
                return ResourceManager.GetString("EditedEntities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lists use rating.
        /// </summary>
        public static string ListsRaitingHeader {
            get {
                return ResourceManager.GetString("ListsRaitingHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List and folder usage ratings and timings..
        /// </summary>
        public static string ListsRaitingTooltip {
            get {
                return ResourceManager.GetString("ListsRaitingTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opened.
        /// </summary>
        public static string UsesLists {
            get {
                return ResourceManager.GetString("UsesLists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version edit operations.
        /// </summary>
        public static string VersionEditEntities {
            get {
                return ResourceManager.GetString("VersionEditEntities", resourceCulture);
            }
        }
    }
}
